# Docker Compose override for local development
# This file is automatically used when running docker-compose up
# in development environments

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for hot reloading
      - ./backend:/app
      # Preserve virtual environment
      - /app/venv
      - ./backend/logs:/app/logs
    environment:
      # Development overrides
      DEBUG: true
      LOG_LEVEL: DEBUG
      SCRAPING_DELAY_MIN: 1.0
      SCRAPING_DELAY_MAX: 2.0
      DEBUG_SCRAPING: true
    command: ["uvicorn", "main:socket_app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      # Preserve node_modules
      - /app/node_modules
      - /app/.next
    environment:
      # Development overrides
      NODE_ENV: development
      NEXT_PUBLIC_APP_NAME: MercadoSniper Dev
      NEXT_PUBLIC_APP_VERSION: 1.0.0-dev
      WATCHPACK_POLLING: true
    command: ["npm", "run", "dev"]

  mongo:
    environment:
      # Development database credentials
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword
      MONGO_INITDB_DATABASE: mercadosniper_dev
    volumes:
      - mongo_dev_data:/data/db

  redis:
    # No password for development
    command: redis-server --appendonly yes 